
sources:
  - name: raw
    schema: gz_raw_data
    loader: bigquery
    tables:
      - name: product
        identifier: raw_gz_product
        columns:
          - name: products_id
            tests:
            - unique
            - not_null
          - name: purchase_cost
      - name: sales
        identifier: raw_gz_sales
        tests:
          - unique:
              column_name: "(orders_id || '-'  || pdt_id)"
        columns:
          - name: date_date
          - name: orders_id
      - name: ship
        identifier: raw_gz_ship
        columns:
          - name: orders_id
            tests:
            - unique
            - not_null
          - name: shipping_fee
          - name: logcost
          - name: ship_cost
  


